# Generated by Django 3.0.6 on 2020-05-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbol',
            name='value',
            field=models.CharField(max_length=200, verbose_name='caracteristica'),
        ),
    ]
