# Generated by Django 3.0.6 on 2020-05-29 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arbol', '0006_auto_20200528_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='longitud',
        ),
    ]
