# Generated by Django 3.0.6 on 2020-05-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbol', '0007_remove_formulario_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='value',
            field=models.IntegerField(default=3, verbose_name='Valor'),
            preserve_default=False,
        ),
    ]
