# Generated by Django 3.0.6 on 2020-05-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbol', '0008_formulario_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='value',
            field=models.IntegerField(default=0, verbose_name='Valor'),
        ),
    ]
