# Generated by Django 3.0.6 on 2020-05-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbol', '0010_remove_formulario_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbol',
            name='cupo',
            field=models.IntegerField(default=0, verbose_name='Cupo'),
            preserve_default=False,
        ),
    ]
