# Generated by Django 3.0.6 on 2020-05-29 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arbol', '0011_arbol_cupo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arbol',
            old_name='type',
            new_name='tipo',
        ),
    ]
